# Generated by Django 3.2.16 on 2024-07-09 15:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',), 'verbose_name': 'пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='users_images', verbose_name='Аватарка'),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, verbose_name='Обо мне'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='users_images', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin'), ('moderator', 'moderator')], default='user', max_length=9, verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, help_text='Идентификатор страницы для URL; разрешены символы латиницы, цифры, дефис и подчёркивание.', unique=True, verbose_name='Идентификатор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='visibility',
            field=models.CharField(choices=[('open', 'open'), ('close', 'clise'), ('only_login', 'only_login')], default='close', max_length=10, verbose_name='Видимость'),
        ),
        migrations.AddField(
            model_name='user',
            name='visibility_in_group',
            field=models.CharField(choices=[('open', 'open'), ('only_login', 'only_login')], default='only_login', max_length=10, verbose_name='Видимость в группе'),
        ),
    ]
