# Generated by Django 3.2.16 on 2024-08-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240815_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', upload_to='users_images', verbose_name='Картинка'),
        ),
    ]
