# Generated by Django 3.2.16 on 2024-08-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='height_field',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
