# Generated by Django 3.2.16 on 2024-08-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_height_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height_field',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
